# Generated by Django 3.2 on 2023-01-03 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="адрес"
                    ),
                ),
                ("latitude", models.FloatField(max_length=6, verbose_name=" Широта")),
                ("longitude", models.FloatField(max_length=6, verbose_name=" Долгота")),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата запроса"
                    ),
                ),
            ],
        ),
    ]
