# Generated by Django 3.2 on 2022-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_alter_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="comment",
            field=models.TextField(
                blank=True, default="", max_length=512, verbose_name="комментарий"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("UN", "НЕОБРАБОТАННО"),
                    ("PG", "В СБОРКЕ"),
                    ("DV", "В ДОСТАВКЕ"),
                    ("CM", "ГОТОВО"),
                ],
                db_index=True,
                default="UN",
                max_length=120,
                verbose_name="статус",
            ),
        ),
    ]
